services:
  lil-t:
    healthcheck:
      test:
        - CMD
        - node
        - -e
        - 'fetch("http://127.0.0.1:3000/api/health").then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))'
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    build: .
    image: lil-t:latest
    container_name: lil-t
    ports:
      - "39093:3000"  # erreichbar unter http://10.0.1.15:39093
    environment:
      - NODE_ENV=production
      - /mnt/user/appdata/lil-t/data:/app/data/app.db
    volumes:
      - /mnt/user/appdata/lil-t/data:/app/data
    restart: unless-stopped
